name: MineDeepRock
main: mine_deep_rock\Main
version: 1.0.0
api: 3.0.0

commands:
  SpawnNPC:
    usage: "/SpawnNPC [NPC]"
    description: "SpawnNPC"
    permission: op
  CreateGame:
    usage: "/CreateGame"
    description: "CreateGame"
    permission: op