name: MineDeepRock
main: mine_deep_rock\Main
version: 1.0.0
api: 3.0.0

commands:
  spawnnpc:
    usage: "/spawnnpc [NPC]"
    description: "spawnnpc"
    permission: op
  creategame:
    usage: "/creategame"
    description: "creategame"
    permission: op
  startgame:
    usage: "/startgame"
    description: "startgame"
    permission: op
  view:
    usage: "/view [,tdm]"
    description: "参加しているゲームの参加人数を知りたい/view,TDMの参加人数リストがみたい/view tdm"
  flag:
    usage: "/flag"
    description: "setting flag"
    permission: op
  core:
    usage: "/core"
    description: "setting core"
    permission: op
  vs:
    usage: "/vs [username]"
    description: "send OneOnOne request"
    permission: op
  requests:
    usage: "/requests"
    description: "one on one request list"
  givemoney:
    usage: "/givemoney [player name] amount"
    description: "givemoney"
    permission: op
  givexp:
    usage: "/givexp [player name] amount"
    description: "givexp"
    permission: op